name: Update Subscriptions

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # ADDED: This block grants the job write permissions to your repository.
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script to get subscriptions
        env:
          LOUWANGZHIYU_EMAIL: ${{ secrets.LOUWANGZHIYU_EMAIL }}
          LOUWANGZHIYU_PASSWORD: ${{ secrets.LOUWANGZHIYU_PASSWORD }}
          DABAI_EMAIL: ${{ secrets.DABAI_EMAIL }}
          DABAI_PASSWORD: ${{ secrets.DABAI_PASSWORD }}
          IKUUU_EMAIL: ${{ secrets.IKUUU_EMAIL }}
          IKUUU_PASSWORD: ${{ secrets.IKUUU_PASSWORD }}
          WWN_EMAIL: ${{ secrets.WWN_EMAIL }}
          WWN_PASSWORD: ${{ secrets.WWN_PASSWORD }}
        run: python main.py

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(subscriptions): Automatic update"
          file_pattern: "subscriptions.txt"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"